### ISSUE TITLE
About external libraries

### ISSUE THREAD

**Issue by mas-suzu** [roborescue/adf-sample-agent-java#13]
I am a member of the AIT-Rescue team.
What should I do if I want to use a external library (open source) that is not originally included in Gradlew.build?
Can I rewrite build.gradle for the addition?
Also, can I use the rewritten build.gradle in the competition?

**Comment by gnardin** [comment]
@mas-suzu 
We changed the `build.grade` to include the `jar` files in the `lib` directory. Thus, you do not need to change the `build.gradle` yourself.
This gradle configuration will be used in the competitions. So, you just need to provide the `lib` directory with the custom `jar`s in the competition together with your team source code.

**Comment by modaresimr** [comment]
@gnardin Isn't it better to allow users to add their own build.gradle? and then we include it in the main build.gradle?
|build.gradle
|----lib
........|-----custom-lib-build.gradle

**Comment by gnardin** [comment]
@modaresimr 
It is simpler to include `lib` in the path of libraries in our `build.gradle`. We allow teams to use custom libraries and we avoid any problem teams may include in their custom `build.gradle`.

**Comment by mas-suzu** [comment]
@gnardin Problem solved. Thank you very much.
