### ISSUE TITLE
gradlew problem

### ISSUE THREAD

**Issue by 2661348402** [roborescue/adf-sample-agent-java#15]
The problem occurs when I try ./gradlew build，how do i solve it？
![图片](https://user-images.githubusercontent.com/80761477/160278134-07fac3cb-f6dd-4806-95f4-3ade06ea610c.png)
)

**Comment by tkmnet** [comment]
The version of java code is specified as 17 in build.gradle.
So you will solve the problem by installing OpenJDK-17 or later.

**Comment by 2661348402** [comment]
Why we can't run the team's previous code, what's the problem
![图片](https://user-images.githubusercontent.com/80761477/160384638-ce0f6275-24ae-4fc9-acd1-7e0180d59dfb.png)
![图片](https://user-images.githubusercontent.com/80761477/160384711-0570ca3f-b6d0-444f-addd-1e1c019db3e3.png)

**Comment by 2661348402** [comment]
Does the new version only include the sample team in the source code, which is very different from the previous source code, how do we integrate them together
![图片](https://user-images.githubusercontent.com/80761477/160810639-66fecdc7-dc8a-4791-96db-5a08648dc16a.png)
![图片](https://user-images.githubusercontent.com/80761477/160810774-8daa10ab-5286-4958-8224-b48b32ce6a15.png)
